name: Build app

on:
  push:
    branches:
      - main
      - switch-rewrite
  pull_request:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fortheusers/sealeo:latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Build ${{ matrix.platform }}
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: wiiu-space.wuhb
        path: /__w/wiiu-space/wiiu-space/wiiu-space.wuhb