name: Build wiiu/switch apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: wiiu
            ext: wuhb
          - platform: switch
            ext: nro
    container:
      image: ghcr.io/fortheusers/sealeo:latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - if: matrix.platform == 'wiiu'
      name: Build wiiu app
      run: make
    - if: matrix.platform == 'switch'
      name: Build switch app
      run: make -f Makefile.switch
    - uses: actions/upload-artifact@v4
      with:
        name: wiiu-space.${{ matrix.ext }}
        path: /__w/wiiu-space/wiiu-space/wiiu-space.${{ matrix.ext }}